#!/usr/bin/python

import download
import sys
import compression
import rename
import copy
import what
import go
import tell
import push
import update
import google

class Hey:
    def __init__(self):
        self.keywords = {
        
            "download":download.download,
            "compress":compression.compress,
            "decompress":compression.decompress,
            "rename":rename.rename,
            "copy":copy.copy,
            "what":what.what,
            "go":go.go,
            "tell":tell.tell,
            "push":push.push,
            "update":update.update,
            "google":google.google,
            "googling":google.google, # Just a different possible word
        }

    
    def parse(self):
        valid = False
        string = sys.argv[1:]
        for x in string:
            if x in self.keywords:
                valid = True
                self.keywords[x](' '.join(string))
                
        if not valid:
            print "Sorry, I didn't understand your command."



if __name__ == "__main__":
    Hey().parse()
