#!/usr/bin/python

#Import Readline module for the console.
import readline

import download
import sys
import compression
import rename
import copy
import what
import go
import tell
import push
import update
import google
import directions
import find



class Console:
        def __init__(self):
            pass

        def start(self):
            print "Welcome to Hey Console. Type 'quit' to exit."
            while(1):
                string = raw_input("Hey>")
                string = string.strip()
                if string == 'quit':
                    exit()
                string = string.split()
                Hey().parse(string)


class Hey:
    #Used to differentiate between terminal input and console.
    console  = False

    def __init__(self):
        self.keywords = {
        
            "download":download.download,
            "compress":compression.compress,
            "decompress":compression.decompress,
            "rename":rename.rename,
            "copy":copy.copy,
            "what":what.what,
            "go":go.go,
            "tell":tell.tell,
            "push":push.push,
            "pull":push.pull,
            "clone":push.clone,
            "update":update.update,
            "google":google.google,
            "googling":google.google, # Just a different possible word
            "directions":directions.directions,
            "find":find.find,
            }
    def setTerminal(self,val):
        #Will set value to the console variable
        #If console it 0 it is a terminal input else console
        console = val
        
    def parse(self, string=0):
        valid = False
        #Use input from sys.argv only if input given from terminal.
        print string
        if self.console:
            string = sys.argv[1:]
            print string
        for x in string:
            if x in self.keywords:
                valid = True
                self.keywords[x](' '.join(string))
                
        if not valid:
            print "Sorry, I didn't understand your command."



if __name__ == "__main__":
    if len(sys.argv) == 1:
        Hey().setTerminal(True)
        Cons = Console()
        Cons.start()
    else:
        Hey().parse()
